
project_id = "kzznbfbwhmgvnqcjontq"

[api]
enabled = true
port = 54321
schemas = ["public", "storage"]

[db]
port = 54322

[studio]
port = 54323

[auth]
enabled = true

[inbucket]
enabled = true
port = 54324

[storage]
enabled = true

[functions]
[functions.mikrotik-proxy]
verify_jwt = true
