
# Docker Compose para modo SELF-HOSTED COMPLETO
# Use este arquivo para rodar tudo localmente:
# - Aplicação WireDash
# - Banco de dados PostgreSQL
# - Sem dependências externas
#
# Para usar:
# 1. Construa a imagem: docker build -t wiredash-local .
# 2. Execute: docker-compose -f docker-compose.selfhosted.yml up -d

version: '3.8'

services:
  # Aplicação WireDash
  wiredash-app:
    image: wiredash-local:latest  # Usa imagem local construída
    container_name: wiredash-selfhosted
    restart: unless-stopped
    ports:
      - "8080:80"
    environment:
      - NODE_ENV=production
      - VITE_USE_LOCAL_SUPABASE=false
      - VITE_SELF_HOSTED=true
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - wiredash-network

  # Banco de dados PostgreSQL
  postgres:
    image: postgres:16
    container_name: wiredash-postgres-selfhosted
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: wireguard_manager
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init-db.sql:/docker-entrypoint-initdb.d/init-db.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - wiredash-network

volumes:
  postgres_data:
    driver: local

networks:
  wiredash-network:
    driver: bridge
