
# Docker Compose principal - Self-Hosted
# Para iniciar o sistema: docker-compose up -d

version: '3.8'
services:
  # Aplicação WireDash
  wiredash-app:
    image: wiredash-local:latest
    container_name: wiredash-selfhosted
    restart: unless-stopped
    ports:
      - "8080:80"
    environment:
      - NODE_ENV=production
      - VITE_USE_LOCAL_SUPABASE=false
      - VITE_SELF_HOSTED=true
      - POSTGRES_HOST=postgres
      - POSTGRES_PORT=5432
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - wiredash-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost/"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 60s

  # Banco de dados PostgreSQL
  postgres:
    image: postgres:16
    container_name: wiredash-postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: wireguard_manager
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init-db.sql:/docker-entrypoint-initdb.d/init-db.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 30s
    networks:
      - wiredash-network

volumes:
  postgres_data:
    driver: local

networks:
  wiredash-network:
    driver: bridge
